version: "3"

services:
  django_service:
    volumes:
      - static:/static
    env_file:
      - .env
    build: .
    ports:
      - "8000:8000"
    networks:
      mynet:
        aliases:
          - beautymanage.ru
  nginx:
    build: ./nginx
    volumes:
    - static:/static
    ports:
      - "80:80"
    depends_on:
      - django_service
    networks:
      - mynet

volumes:
  static:

networks:
  mynet: