# Generated by Django 4.0.1 on 2022-06-02 17:36

from django.db import migrations, models
import django.db.models.deletion
import office.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(help_text='Название должно быть уникальным.', max_length=100, unique=True, verbose_name='Название услуги')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена')),
                ('duration', models.IntegerField(help_text='Введите длительность услуги в минутах.', verbose_name='Длительность услуги')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('client', models.ForeignKey(limit_choices_to={'role': 'C'}, null=True, on_delete=models.SET(office.models.get_deleted_user), to='main.profile', verbose_name='Клиент')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='office.service', verbose_name='Услуга')),
                ('shift', models.ForeignKey(limit_choices_to={'date': models.DateField(verbose_name='Дата')}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='office.shift', verbose_name='Смена')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
    ]
