# Generated by Django 4.0.1 on 2022-06-02 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0006_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='office.shift', verbose_name='Смена'),
        ),
    ]
