# Generated by Django 4.0.1 on 2022-06-07 10:04

from django.db import migrations, models
import office.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('office', '0008_alter_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(limit_choices_to={'role': 'C'}, null=True, on_delete=models.SET(office.models.get_deleted_user_c), to='main.profile', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='master',
            field=models.ForeignKey(limit_choices_to={'role': 'E'}, on_delete=models.SET(office.models.get_deleted_user_e), to='main.profile', verbose_name='Мастер смены'),
        ),
    ]
