# Generated by Django 4.0.1 on 2022-06-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0009_alter_appointment_client_alter_shift_master'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('client', 'date', 'time'), name='unique_appointment'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(fields=('date', 'master'), name='unique_shift'),
        ),
    ]
