# Generated by Django 4.0.1 on 2022-06-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0010_appointment_unique_appointment_shift_unique_shift'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('shift', 'time'), name='unique_shift_time'),
        ),
    ]
