# Generated by Django 4.0.1 on 2022-04-29 19:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message="Номер телефона необходимо вводить в формате: '+79991234567'.", regex='^\\+?7?\\d{9}$')], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('C', 'клиент'), ('E', 'сотрудник'), ('A', 'администратор')], default='C', max_length=1, verbose_name='Роль'),
        ),
    ]
