# Generated by Django 4.0.1 on 2022-04-29 21:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_phone_number_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message="Номер телефона необходимо вводить в формате: '+79991234567'.", regex='^\\+?7?\\d{10}$')], verbose_name='Телефон'),
        ),
    ]
