# Generated by Django 4.0.1 on 2022-04-30 11:12

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message="Номер телефона необходимо вводить в формате: '+79991234567'.", regex='^\\+?7?\\d{9,10}$')], verbose_name='Телефон'),
        ),
        migrations.CreateModel(
            name='Shifts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('status', models.CharField(choices=[('N', 'Не подтверждено'), ('S', 'Подтверждено')], default='N', max_length=1, verbose_name='Статус смены')),
                ('master', models.ForeignKey(limit_choices_to={'role': 'E'}, on_delete=models.SET(profiles.models.get_deleted_user), to='profiles.profile', verbose_name='Мастер смены')),
            ],
        ),
    ]
