# Generated by Django 4.0.1 on 2022-05-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_shift_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='room',
            field=models.CharField(choices=[('1', 'Парикмахерский'), ('2', 'Маникюрный')], default='1', max_length=1, verbose_name='Зал смены'),
        ),
    ]
